delimiter $$

CREATE TABLE `allocation` (
  `ALLOCATION_ID` varchar(45) NOT NULL,
  `ROW` int(11) NOT NULL,
  `COL` int(11) NOT NULL,
  `VAL` double DEFAULT NULL,
  PRIMARY KEY (`ALLOCATION_ID`,`ROW`,`COL`),
  KEY `ALLOCATION_FK1` (`ALLOCATION_ID`),
  CONSTRAINT `ALLOCATION_FK1` FOREIGN KEY (`ALLOCATION_ID`) REFERENCES `matrix` (`MATRIX_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

