CREATE TABLE `composition` (
  `COMPOSITION_ID` varchar(45) NOT NULL,
  `LHS` varchar(45) DEFAULT NULL,
  `RHS` varchar(45) NOT NULL,
  `POOL_LIST_ID` varchar(45) DEFAULT NULL,
  `DIM` varchar(45) NOT NULL,
  PRIMARY KEY (`COMPOSITION_ID`),
  KEY `COMPOSITION_FK1` (`LHS`),
  KEY `COMPOSITION_FK2` (`RHS`),
  KEY `COMPOSITION_FK3` (`DIM`),
  KEY `COMPOSITION_FK4` (`POOL_LIST_ID`),
  CONSTRAINT `COMPOSITION_FK1` FOREIGN KEY (`LHS`) REFERENCES `composition` (`COMPOSITION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `COMPOSITION_FK2` FOREIGN KEY (`RHS`) REFERENCES `allocation` (`ALLOCATION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `COMPOSITION_FK3` FOREIGN KEY (`DIM`) REFERENCES `dimension` (`DIMENSION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `COMPOSITION_FK4` FOREIGN KEY (`POOL_LIST_ID`) REFERENCES `pool_list` (`POOL_LIST_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$