delimiter $$

CREATE TABLE `dimension` (
  `DIMENSION_ID` varchar(45) NOT NULL,
  `ROW` int(11) NOT NULL,
  `COL` int(11) NOT NULL,
  `DESC` varchar(45) NOT NULL,
  PRIMARY KEY (`DIMENSION_ID`,`ROW`,`COL`,`DESC`),
  KEY `DIMENSION_FK1` (`DIMENSION_ID`),
  CONSTRAINT `DIMENSION_FK1` FOREIGN KEY (`DIMENSION_ID`) REFERENCES `matrix` (`MATRIX_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

