delimiter $$

CREATE TABLE `pool_list` (
  `POOL_LIST_ID` varchar(45) NOT NULL,
  `COMPOSITION_ID` varchar(45) NOT NULL,
  PRIMARY KEY (`POOL_LIST_ID`,`COMPOSITION_ID`),
  KEY `POOL_FK1` (`COMPOSITION_ID`),
  CONSTRAINT `POOL_FK1` FOREIGN KEY (`COMPOSITION_ID`) REFERENCES `composition` (`COMPOSITION_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

